### ISSUE TITLE
Ignoring of xhtml files with spaces in the name

### ISSUE THREAD

**Issue by MarvNC** [xavdid/epub-wordcount#7] opened 2020-07-17 04:38 UTC
If an html file within an epub has spaces, it will not have its words counted. For example, in the image below, chapters 1 and 2 will not have their words counted by this tool. 
![image](https://user-images.githubusercontent.com/17340496/87749093-894c4200-c7ac-11ea-832d-3104ad2e81c7.png)

**Comment by xavdid** [comment] 2020-07-19 21:07
This is probably an issue with https://github.com/julien-c/epub, since this counts all the files it finds. Does the book's manifest correctly link to the filenames? If so, could you send me a copy of the book and I'll see if I can work around it?

**Comment by MarvNC** [comment] 2020-07-21 04:21
I came across this issue while editing an ebook with Sigil, so it could be an issue with the way that application saves files. 
Those sections in the manifest: 
![image](https://user-images.githubusercontent.com/17340496/88012325-7304f580-cace-11ea-87e8-ac7d5c882be4.png)
[The World of Otome Games is Tough for Mobs v01 [2Slow2Late].zip](https://github.com/xavdid/epub-wordcount/files/4951277/The.World.of.Otome.Games.is.Tough.for.Mobs.v01.2Slow2Late.zip)
83,379 words according to epub-wordcount when all xhtml files are properly named, and 68,804 words after renaming.

**Comment by xavdid** [comment] 2020-07-21 04:24
Got it! i'll take a look in the epub parser and see if anything jumps out.

**Comment by xavdid** [comment] 2020-07-22 07:06
Ok! So I think the issue is that your epub isn't properly structured. 

The `href` is `Text/Chapter%201.xhtml`. The `%20` is correctly translated by browsers as a space, but the zipfile tool that that the epub parser uses under the hood doesn't handle them correctly. I'm not sure if that's a bug or intended behavior, but you can file an issue with them [on their repo](https://github.com/mapbox/node-zipfile) if you'd like

In any case, if you've got control over the file and the manifest, I'd update the chapter files not to have spaces in them and update the manifest accordingly.

Given that `epub-wordcount` correctly mentions there's an error (when run with `DEBUG=* word-count ...`), I'm going to close this. I will make a note to make it more clear that there were silent errors though, as that is currently a confusing experience.

If the zip library releases and update that makes it compatible with spaces in the name, let me know here and I'll update my dependencies. 

Thanks!

**Closed by xavdid** 2020-07-22 07:06 UTC
